In [2]:
!uv add pandas

Resolved 179 packages in 0.70ms
Audited 150 packages in 0.85ms

In [3]:
import pandas as pd

In [6]:
df = pd.read_excel("../__data__/products_data.xlsx")

In [8]:
df.head()

,id,PRODUCT_NAME,PRODUCT_CATEGORY_id,PRODUCT_CATALOGUE_NUMBER,PRODUCT_HSN_NO,PRODUCT_VIDEO_LINK,PRODUCT_DESCRIPTION,PRODUCT_SPECS_FILE,ACTUAL_FILENAME,TITLE,IS_APPROVED,IS_REJECTED,SELLER_id,THUMBNAIL_IMAGE,MIN_PRICE,MAX_PRICE,STATUS,REASON,CREATED_AT,UPDATED_AT
0,2,Busbx,5,NaN,NaN,NaN,Ubwhx,NaN,NaN,NaN,True,False,6,buyer_seller/seller/seller_SEL6929773/Busbx/pr...,NaN,NaN,Inactive,NaN,2025-06-30 08:47:03.350,2025-06-30 08:49:35.216
1,5,Digital camera,5,NaN,NaN,NaN,Digital camera. A digital camera is an electro...,NaN,NaN,NaN,True,False,6,buyer_seller/seller/seller_SEL6929773/Digital ...,NaN,NaN,Inactive,NaN,2025-06-30 09:00:48.672,2025-07-21 07:29:13.882
2,7,headphones,5,NaN,NaN,NaN,With Mic:Yes\r\nBEAST Mode: Experience lag-fre...,buyer_seller/seller/seller_SEL7964129/headphon...,NaN,NaN,True,False,12,buyer_seller/seller/seller_SEL7964129/headphon...,2000.0,2500.0,Active,NaN,2025-07-03 10:33:06.311,2025-07-03 10:33:06.311
3,8,Samsung Tv,5,NaN,NaN,NaN,Samsung 80 cm (32 Inch) HD Ready LED Smart\n\n...,NaN,NaN,NaN,True,False,12,buyer_seller/seller/seller_SEL7964129/Samsung ...,NaN,NaN,Active,NaN,2025-07-10 10:52:32.482,2025-07-10 10:52:32.482
4,9,Cameras,5,NaN,NaN,NaN,Teyh,NaN,NaN,NaN,True,False,12,buyer_seller/seller/seller_SEL7964129/Cameras/...,NaN,NaN,Inactive,NaN,2025-07-11 08:57:32.188,2025-07-11 09:05:21.333

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        111 non-null    int64
 1   PRODUCT_NAME              111 non-null    object
 2   PRODUCT_CATEGORY_id       111 non-null    int64
 3   PRODUCT_CATALOGUE_NUMBER  0 non-null      float64
 4   PRODUCT_HSN_NO            0 non-null      float64
 5   PRODUCT_VIDEO_LINK        0 non-null      float64
 6   PRODUCT_DESCRIPTION       111 non-null    object
 7   PRODUCT_SPECS_FILE        2 non-null      object
 8   ACTUAL_FILENAME           0 non-null      float64
 9   TITLE                     0 non-null      float64
 10  IS_APPROVED               111 non-null    bool
 11  IS_REJECTED               111 non-null    bool
 12  SELLER_id                 111 non-null    int64
 13  THUMBNAIL_IMAGE           111 non-null    object
 14  MIN_PRICE                 2 non-null      float64
 15  MAX_PRICE                 2 non-null      float64
 16  STATUS                    111 non-null    object
 17  REASON                    0 non-null      float64
 18  CREATED_AT                111 non-null    datetime64[ns]
 19  UPDATED_AT                111 non-null    datetime64[ns]
dtypes: bool(2), datetime64[ns](2), float64(8), int64(3), object(5)
memory usage: 16.0+ KB

In [10]:
df.describe()

,id,PRODUCT_CATEGORY_id,PRODUCT_CATALOGUE_NUMBER,PRODUCT_HSN_NO,PRODUCT_VIDEO_LINK,ACTUAL_FILENAME,TITLE,SELLER_id,MIN_PRICE,MAX_PRICE,REASON,CREATED_AT,UPDATED_AT
count,111.000000,111.000000,0.0,0.0,0.0,0.0,0.0,111.000000,2.000000,2.000000,0.0,111,111
mean,59.963964,11.918919,NaN,NaN,NaN,NaN,NaN,21.027027,1750.000000,2250.000000,NaN,2025-10-04 18:14:19.353936896,2025-10-08 00:56:41.397504512
min,2.000000,2.000000,NaN,NaN,NaN,NaN,NaN,6.000000,1500.000000,2000.000000,NaN,2025-06-30 08:47:03.350000,2025-06-30 08:49:35.216000
25%,32.500000,5.000000,NaN,NaN,NaN,NaN,NaN,12.000000,1625.000000,2125.000000,NaN,2025-10-15 06:51:28.932000256,2025-10-15 07:00:17.131500032
50%,60.000000,15.000000,NaN,NaN,NaN,NaN,NaN,16.000000,1750.000000,2250.000000,NaN,2025-10-15 09:31:27.265999872,2025-10-15 09:33:58.353999872
75%,87.500000,20.000000,NaN,NaN,NaN,NaN,NaN,36.000000,1875.000000,2375.000000,NaN,2025-10-15 11:18:57.286000128,2025-10-15 11:26:28.913999872
max,115.000000,26.000000,NaN,NaN,NaN,NaN,NaN,43.000000,2000.000000,2500.000000,NaN,2025-10-15 12:53:46.848000,2025-10-15 12:53:46.848000
std,32.250138,8.546275,NaN,NaN,NaN,NaN,NaN,13.201556,353.553391,353.553391,NaN,NaN,NaN

In [11]:
df.columns

Index(['id', 'PRODUCT_NAME', 'PRODUCT_CATEGORY_id', 'PRODUCT_CATALOGUE_NUMBER',
       'PRODUCT_HSN_NO', 'PRODUCT_VIDEO_LINK', 'PRODUCT_DESCRIPTION',
       'PRODUCT_SPECS_FILE', 'ACTUAL_FILENAME', 'TITLE', 'IS_APPROVED',
       'IS_REJECTED', 'SELLER_id', 'THUMBNAIL_IMAGE', 'MIN_PRICE', 'MAX_PRICE',
       'STATUS', 'REASON', 'CREATED_AT', 'UPDATED_AT'],
      dtype='object')

In [15]:
df[["id", "PRODUCT_NAME", "PRODUCT_CATEGORY_id", "PRODUCT_DESCRIPTION"]].head()

,id,PRODUCT_NAME,PRODUCT_CATEGORY_id,PRODUCT_DESCRIPTION
0,2,Busbx,5,Ubwhx
1,5,Digital camera,5,Digital camera. A digital camera is an electro...
2,7,headphones,5,With Mic:Yes\r\nBEAST Mode: Experience lag-fre...
3,8,Samsung Tv,5,Samsung 80 cm (32 Inch) HD Ready LED Smart\n\n...
4,9,Cameras,5,Teyh